version: 2
updates:
  - package-ecosystem: "npm"
    directoy: "/"
    schedule:
      interval: "daily"
    assignees:
      - "Timeraa"
    commit-message:
      prefix: "ğŸ”¼"
      prefix-development: "ğŸ”¼"
    labels:
      - "dependencies"
    open-pull-requests-limit: 15
